config/routes.rb
Rails.application.routes.draw do
  get 'screenshots/index'

  get '/sign_out', to: "sessions#destroy"
  get '/sign_in', to: "sessions#new", as: :sign_in
  get '/sessions/new', to: "sessions#new"

  get '/about', to: 'pages#about', as: :about

  resource :session, only: [:create]
  resources :game_sessions do
    member do
      post 'start'
      post 'reset'
      get 'staging'
    end
  end

  get '/verse_answers/:id', to: "verse_answers#show", as: :verse_answer

  resources :chats, only: [:new, :create, :show]

  resources :book_guesses, only: [:create]
  resources :chapter_guesses, only: [:create]
  resources :verse_guesses, only: [:create]

  resources :user_game_sessions, only: [:create, :destroy]

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  root "game_sessions#index"
end

app/models/broadcast/game_session.rb
include ActionView::RecordIdentifier
module Broadcast
  class GameSession

    def self.add_to_index(game_session)
      new(game_session).add_to_index
    end

    def self.update(game_session)
      new(game_session).update
    end

    def initialize(game_session)
      @game_session = game_session
    end

    def add_to_index
      Turbo::StreamsChannel.broadcast_prepend_later_to(
        "guessref",
        target: "game_sessions",
        html: game_session_badge
      )
    end

    def update
      Turbo::StreamsChannel.broadcast_replace_later_to(
        @game_session,
        target: "game-session-show",
        html: game_session_component
      )
    end

    private

    attr_reader :game_session

    def game_session_component
      ApplicationController.render(
        GameSessionComponent.new(game_session: @game_session),
        layout: false
      )
    end

    def game_session_badge
      ApplicationController.render(
        GameSessionBadgeComponent.new(game_session: @game_session),
        layout: false
      )
    end
  end
end

app/models/game_session.rb
class GameSession < ApplicationRecord

  # broadcasts partial: :game_session_badge

  after_create_commit -> {
    Broadcast::GameSession.add_to_index(self)
  }
  after_update_commit -> {
    Broadcast::GameSession.update(self)
  }

  has_many :game_rounds, dependent: :destroy
  has_many :user_game_sessions, dependent: :destroy
  has_many :users, through: :user_game_sessions
  has_many :chat_messages, dependent: :destroy
  has_many :user_answers, dependent: :destroy
  has_many :verses, through: :game_rounds
  has_one :score_board, dependent: :destroy

  validates :name, presence: true

  LOADING_STATUS = 'LOADING'
  LOBBY_STATUS = 'LOBBY'
  ACTIVE_STATUS= 'ACTIVE'
  COMPLETED_STATUS = 'COMPLETED'
  STATUSES = [LOADING_STATUS, LOBBY_STATUS, ACTIVE_STATUS, COMPLETED_STATUS]

  scope :recent, -> { where("created_at > ?", 600.minutes.ago) }
  scope :loading, -> { where(status: LOADING_STATUS) }
  scope :lobby, -> { where(status: LOBBY_STATUS) }
  scope :active, -> { where(status: ACTIVE_STATUS) }
  scope :completed, -> { where(status: COMPLETED_STATUS) }
  scope :active_and_lobby, -> { where(status: [LOADING_STATUS, LOBBY_STATUS, ACTIVE_STATUS]) }

  def tick!
    if lobby?
      lobby_tick!
    elsif active?
      active_tick!
    elsif completed?
      completed_tick!
    else
      raise "game session has unknown status should not have status #{self.status}"
    end
  end

  def lobby_tick!
    active!
    # GameSessionTickJob.set(wait: 3.seconds).perform_later(self.id)
    GameSessionTickJob.perform_later(self.id)
  end

  def active_tick!
    if current_round
      # GameRoundTickJob.set(wait: 3.seconds).perform_later(current_round.id)
      GameRoundTickJob.perform_later(current_round&.id)
    else
      completed!
    end
  end

  def completed_tick!
    # nothing?
  end

  def current_round
    remaining_rounds.first
  end

  def num_rounds
    game_rounds.count
  end

  def num_verses
    game_rounds.sum(&:num_verses)
  end

  def remaining_rounds
    game_rounds.active + game_rounds.queued
  end

  # def fill_in_game_info # this is temporary
  #   3.times do
  #     game_rounds.create(status: GameRound::QUEUED_STATUS)
  #   end
  #
  #   game_rounds.each do |game_round|
  #     5.times do
  #       verse = game_round.verses.create
  #       verse.random_from_fixture
  #     end
  #   end
  #   self
  # end

  def lobby?
    self.status == LOBBY_STATUS
  end

  def active?
    self.status == ACTIVE_STATUS
  end

  def completed?
    self.status == COMPLETED_STATUS
  end

  def broadcast_update
    Broadcast::GameSession.update(self)
  end

  def retrieved?
    # this is just awful hack to keep from premature clicking
    verses.count == 5
  end

  private

  def active!
    update_attribute(:status, ACTIVE_STATUS)
  end

  def completed!
    update_attribute(:status, COMPLETED_STATUS)
  end

  def close_game
    update_attribute(:status, COMPLETED_STATUS)
  end

end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController

  skip_before_action :authenticate!, only: [:index]

  def index
    @game_sessions = GameSession.recent.order(:created_at).reverse_order
  end

  def show
    @game_session = GameSession.find params[:id]
    current_user.game_sessions << @game_session unless current_user.game_sessions.include? @game_session
    render layout: 'no_nav'
  end

  def new
  end

  def create
    game_session = GameSession.new(name: params[:name], status: GameSession::LOBBY_STATUS)
    if game_session.valid?
      game_session.save
      game_session.users << current_user
      game_session.create_score_board!

      BuildsGameSessionStructureJob.perform_later(game_session.id)

      redirect_to game_session_path(game_session)
    else
      render :new
    end
  end

  def reset
    @game_session = GameSession.find params[:id]
    @game_session.update!(status: GameSession::LOBBY_STATUS)
    @game_session.score_board.reset_scores
    @game_session.game_rounds.each {|gr| gr.destroy}
    BuildsGameSessionStructureJob.perform_later(@game_session.id)
    redirect_to game_session_path(@game_session)
  end
    


  def start
    game_session = GameSession.find params[:id]
    if game_session && game_session.retrieved?
      game_session.tick! 
      redirect_to game_session_path(game_session)
    end
  end
end

app/views/game_sessions/_game_session.html.haml
= render(GameSessionComponent.new(game_session: @game_session))

app/views/game_sessions/_game_session_badge.html.haml
= render(GameSessionBadgeComponent.new(game_session: game_session)

app/views/game_sessions/_game_session_li.html.haml
%li.col-span-1.flex.shadow-sm.rounded-md
  .flex-shrink-0.flex.items-center.justify-center.w-24.bg-pink-600.text-white.text-sm.font-medium.rounded-l-md Lobby
  .flex-1.flex.items-center.justify-between.border-t.border-r.border-b.border-gray-200.bg-white.rounded-r-md.truncate
    .flex-1.px-4.py-2.text-sm.truncate
      %a.text-gray-900.font-medium.hover:text-gray-600{:href => game_session_path(game_session)}
        = game_session.name || "Game Name"
      %p.text-gray-500
        = "16 Players"
    .flex-shrink-0.pr-2#show-game-session-button
      = link_to game_session_path(game_session) do
        %button.w-8.h-8.bg-white.inline-flex.items-center.justify-center.text-gray-400.rounded-full.bg-transparent.hover:text-gray-500.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-500{:type => "button", :id => dom_id(game_session)}
          %svg.h-6.w-6{:fill => "none", :stroke => "currentColor", "stroke-width" => "2", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M13 5l7 7-7 7M5 5l7 7-7 7", "stroke-linecap" => "round", "stroke-linejoin" => "round"}

app/views/game_sessions/index.html.haml
= turbo_stream_from "guessref"

-# - @game_sessions.each do |game_session|
-#   %p
-#     =game_session.id
-#     =link_to game_session.name, game_session_path(game_session)
-#     =game_session.status
.text-center.font-medium.absolute.w-full.flex.justify-center{class: "bottom-[10%]"}
  #new-game-link.bg-indigo-100.text-white.px-6.py-1.rounded.max-w-md.cursor-pointer{class: "w-5/6"}
    =link_to "New Game", new_game_session_path
%div.px-10.py-5.overflow-scroll{class: "max-h-[75vh]"}
  %h2.text-primary.font-medium.tracking-wide.text-left Recent and Current Games
  %ul#game_sessions.mt-3.grid.grid-cols-1.gap-3.sm:gap-6.sm:grid-cols-2.lg:grid-cols-4{:role => "list"}
    - @game_sessions.each do |game_session|
      = render GameSessionBadgeComponent.new(game_session: game_session)

app/views/game_sessions/new.html.haml
-# #new-game-link.bg-indigo-100.text-white.px-6.py-1.rounded.max-w-md.cursor-pointer{class: "w-5/6"}
-# .bg-white.w-96.py-8.px-4.mx-auto.mt-28.shadow.rounded-lg.sm:px-10.sm:mx-2
%form.space-y-6.px-10.py-5{:action => game_sessions_path, :method => "POST"}
  %div
    %label.block.text-sm.font-medium.text-text-300.text-center.mb-4{:for => "email"} Name your game:
    .mt-1
      %input#game_name.appearance-none.block.w-full.px-3.py-2.border.border-gray-100.rounded-md.shadow.focus:outline-none.focus:ring-indigo-100.focus:border-indigo-100.sm:text-sm{:name => "name", :required => "", :type => "text"}/
  .text-center.font-medium.mb-5.absolute.w-full.max-w-md.flex.justify-center.left-0{class: "bottom-[25%]"}
    %button#create-session.flex.justify-center.py-2.px-4.border.border-transparent.rounded-md.shadow-sm.text-sm.font-medium.text-white.bg-indigo-100.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-indigo-100{class: "w-5/6", :type => "submit"} Create Game

app/views/game_sessions/show.html.haml
= turbo_stream_from @game_session
= render(GameSessionComponent.new(game_session: @game_session))